### ISSUE TITLE
Testing scenarios

### ISSUE THREAD

**Issue by crsdc** [crsdc/badgerapp#11]
Needed for our beta testers. JG working on some and will be sharing them with CF.

**Comment by DawnBadger** [comment]
Please can we have these asap. I just jumped in to do some testing and it is just finger in the air without scenarios.

**Comment by crsdc** [comment]
Scenarios are now up on the testing website, though there are a few more changes to the decision tree and report-building logic in forthcoming versions before users in beta will be able to work every scenario through to its conclusion.
