### ISSUE TITLE
Not connecting to Mail client

### ISSUE THREAD

**Issue by DawnBadger** [crsdc/badgerapp#25]
I tried to submit a report for the first time and couldn't as message said I needed to restore 'Mail' which was no longer on my iphone. I have gmail set up and outlook, so not sure what the problem is. When I click to go to the App store for it it shows me 'Mail' from Apple - which I don't want. How do we get around this? Chris I'll send you the message, as it's on my phone.

**Comment by crsdc** [comment]
By this point we have the email copy and paste facility #58 as a workaround for cases where users' phones don't cooperate with passing the report text to the right email app. I think we've therefore addressed this as far as it being a showstopper for wider release. The ultimate solution would be implementation of a backend #18 which is a consideration for the future.
