### ISSUE TITLE
"Forestry or tree surgery: Happening now" lists irrelevant information

### ISSUE THREAD

**Issue by JessGroling** [crsdc/badgerapp#26]
At the moment it says both "If safe to do so, speak with workers, a site manager or the landowner to find out if a licence was obtained to carry out this work." AND "If safe to do so, speak with the farmer or landowner to find out if a licence was obtained to carry out this work."

The latter needs removing for this scenario.

**Comment by crsdc** [comment]
Fixed in 1.2.24
