### ISSUE TITLE
Evidence checklist for forestry scenario lists irrelevant option

### ISSUE THREAD

**Issue by JessGroling** [crsdc/badgerapp#27]
When going through the forestry sett interference scenario, the evidence checklist includes "The animal in situ" - I don't think this should be there

**Comment by JessGroling** [comment]
I have just spotted that it's also doing this for the 'hunt related sett interference' scenario. "The animal in situ" is not relevant here.

**Comment by crsdc** [comment]
Centralising tracking of this under #47
