### ISSUE TITLE
Add a word to "information you've provided so far"

### ISSUE THREAD

**Issue by JessGroling** [crsdc/badgerapp#31]
Before submitting the report, the user is given a summary incident report which they can edit. When going through the forestry scenario, at the moment under "Information you've provided so far" it says "This is a sett interference incident linked to forestry or tree surgery". Can we add the word 'badger' in front of 'sett'? This may seem pedantic but if this report is forwarded directly to police it would be good to include the word badger at the very start. Obviously this would need to be done for all other scenarios too.

**Comment by crsdc** [comment]
Fixed in 1.2.24
