### ISSUE TITLE
Evidence of badger activity at the sett - prompt to describe sett?

### ISSUE THREAD

**Issue by JessGroling** [crsdc/badgerapp#35]
In the evidence checklist under "Evidence of badger activity at the sett" - could we change the "Add notes" prompt to encourage the user to describe the sett instead, including listing and describing field signs? If we don't have tick boxes next to the 9 field signs then this might be our best way to encourage the user to intentionally document what they see.

**Comment by crsdc** [comment]
Fixed in a previous version
