### ISSUE TITLE
Sending reports - email permissions issue

### ISSUE THREAD

**Issue by JessGroling** [crsdc/badgerapp#36]
When I first started using the app, I was prompted to give Huawei permission to access my Google account. After I did this I was able to successfully send a test report and it subsequently appeared in my sent folder in my Gmail account. 

However, I then removed Huawei's permissions to access my Google account and tried sending a fresh report. It appeared to send this successfully (i.e. the report appeared in an email and I clicked send) but I wasn't sure how it could have sent it given I had removed Huawei's permissions. So I checked my sent folder and this time it did NOT appear in the sent folder, suggesting it did not successfully send. 

So if I hadn't checked my sent folder, I wouldn't have had any reason to suspect the email hadn't sent.

**Comment by crsdc** [comment]
A sort of Huawei version of #25. Addressed with the workaround under #58 so closing for now.
