### ISSUE TITLE
Evidence of badger activity - selection is not intuitive

### ISSUE THREAD

**Issue by kamac13** [crsdc/badgerapp#40]
- Select Sett interference
- Select Badger diggers
- Select 'No' to 'Is someone interfering with the sett right now?'
- Mark location on map
- Select 'Evidence of badger activity at the sett'

This screen includes a list of potential evidence of badger activity.  Seeing that list, my expectation was that clicking on each heading would 'select' that evidence, like a pick list.  However, clicking on each gives information but does not select.  Instead, I have to type in the list of evidence manually. 

More intuitive in my opinion would be the ability to click on a heading to select an evidence type with an Information icon to click on should I need information about the evidence type.   The less manual typing and the more easy clicks the better (a) for speed of entry and (b) to make it easier to give complete information given that the user is likely to be in the field in the cold, wet, wind etc.

**Comment by crsdc** [comment]
Agreed and implemented. Relates to #30. Some changes still to be made to user interface on this screen (esp the "which of the above field signs are present?" question) but the basic interface we wanted is now working.
