### ISSUE TITLE
User warning to activate Location Services for Badger Watcher app

### ISSUE THREAD

**Issue by kamac13** [crsdc/badgerapp#41]
- Select Sett interference
- Select Badger diggers
- Select 'No' to 'Is someone interfering with the sett right now?'
- Mark location on map
- Select 'Evidence of badger activity at the sett'
- Select 'Take photos or videos using Another device'
- Select 'Show time, date and location'. 

The screen only shows the time and date, but not the location.  In a different app on my phone, the GPS location is correctly found. 
![IMG_3411](https://user-images.githubusercontent.com/101217745/157331298-9a54925f-d84b-49e1-8096-5a48fdecf75b.png)_**

**Comment by kamac13** [comment]
EDIT: this was due to Location Services on my iPhone not being switched on for the Badger Watch app even though they are switched on for other purposes.  So not a defect. 

A suggestion might be to include a note to users to activate Location Services for the Badger Watch app.

**Comment by crsdc** [comment]
Looking into this on iPhone

**Comment by crsdc** [comment]
Believed to be fixed now, plus this screen now displays "waiting for GPS", "please enable location" etc instead of just blanking
