### ISSUE TITLE
Typo 'Don' on 'Thank you' page

### ISSUE THREAD

**Issue by kamac13** [crsdc/badgerapp#43]
After having emailed an incident report, the Thank You screen has a button labelled 'Don'.

I assume this is a typo and should be 'Done'
![IMG_3413](https://user-images.githubusercontent.com/101217745/157336409-1480bdce-0a3d-4ea9-8073-8b22ee83710f.png)
?

**Comment by crsdc** [comment]
I believe this was a clipping issue rather than a typo, and has since been fixed, unless wider issues about text sizes continue to cause clipping on some devices, e.g. #24, #3. Thanks for spotting it!
