### ISSUE TITLE
Suggestion for 'Home' button after saving draft report

### ISSUE THREAD

**Issue by kamac13** [crsdc/badgerapp#44]
If I choose to save a draft report, the message tells me the draft has been saved in 'My reports'. 

It would be nice to have a 'Home' button on this screen to go back to the start/My Reports if I choose not to hit 'Next' to continue.  Otherwise I have to go 'back' about 10 screens to get to the Home page.

**Comment by crsdc** [comment]
Agreed. Rolled into #5 re draft saving and wider implementation of home buttons.
