### ISSUE TITLE
Snares text flow

### ISSUE THREAD

**Issue by kamac13** [crsdc/badgerapp#47]
- Select 'Traps or snares'
- Select 'Snare'
- Select 'Snare on a badger run or near a sett'

The next option is asking about information about 'the animal in situ' and it asks for photos of dead or injured badgers.  These questions do not seem relevant in this flow reporting a snare, not an animal in a snare.  This seems to be the same screen as occurs if the user had selected to report 'Dead badger in a snare'. 

I've seen similar unexpected questions on the other flows where I've selected the option that indicates there is not a live or dead badger present.   Eg. in the following flows:

- Leghold trap or body grip trap
- Cage traps
- Other traps
-

**Comment by crsdc** [comment]
Relates to #27

**Comment by crsdc** [comment]
Believed fixed with corrections to selective display of options on the evidence checklist. Problems detailed in #27 also fixed.
