### ISSUE TITLE
Photo handling

### ISSUE THREAD

**Issue by kamac13** [crsdc/badgerapp#53]
I found initially thet I wasn't clear that photos are not being attached/saved with the report.  Admittedly, I can't check what happens if I take the photos via the app as that is disabled - that might make it clearer. 

However, in the absence of being able to check that, I would suggest it might be helpful to make that explicit.  Perhaps where you say 'Store your photos and videos securely. Do not edit...' you could also say that you may be asked to provide them at a later date.  Or suggest that users attach them to the email directly on their phones.

**Comment by crsdc** [comment]
Wording amended on this screen
