### ISSUE TITLE
All instance of 'Map Temp Disabled' need addressing

### ISSUE THREAD

**Issue by DawnBadger** [crsdc/badgerapp#56]
Hit this issue with all scenarios - looks to be when go to 999 outcome and then on that page the map is temp disabled. When go a route that doesn't end in 999 the map is working (but sometimes also still have the pic for 'map temp disabled'. A sweep of all map outcomes is needed to ensure mapping is live and no holding image.

**Comment by crsdc** [comment]
Integration of the mapping module into these screens is pending issue #71 re current clunkiness of the map. Agree all these placeholders need to be replaced with working maps before we go live.

**Comment by crsdc** [comment]
Fix to 999 screen forthcoming as dependency for this issue has since been resolved
