### ISSUE TITLE
Wording of Badger Trust in strings

### ISSUE THREAD

**Issue by crsdc** [crsdc/badgerapp#6]
Request from DV to amend "the Badger Trust" to "Badger Trust".

My request for clarification from 11 Oct:

>Currently the only strings that include this are my placeholder intro blurb which is being replaced [...], and on the screen that says “Please still document and report licensed sett interference to the Badger Trust for their records.” Are we saying this should be “report licensed sett interference to Badger Trust”? I can easily make the change; just checking I understand the intention since BT website home page talks about “reporting incidents to the Badger Trust”.

**Comment by DawnBadger** [comment]
We are Badger Trust, not the/The Badger Trust. Fine also to shorten to 'Trust' but then that would be 'the Trust'

**Comment by crsdc** [comment]
Believed to be all fixed in the app by v1.2.19. Any instances outstanding in App/Play Store metadata will be caught when these are next looked at.
