### ISSUE TITLE
SC7 - Poisoning

### ISSUE THREAD

**Issue by DawnBadger** [crsdc/badgerapp#62]
Home > Poison > Poison page > all three blue buttons on this page are disabled. 

Q - we have posioning covered twice, one directly from Home screen (above) and one via Sett Interference > Poisoning or gassing. This may be intended. Can the Home Page > Poison > be rerouted to follow the SI > P or G route for ease of fix?

**Comment by crsdc** [comment]
To discuss with JG.

**Comment by crsdc** [comment]
Poison tree now enabled.

The apparent duplication is intended and is aimed at covering all bases for users reporting poison. Not all poison-related reports are necessarily sett interference incidents. Where a user starts with the general poison category, indicates they have found a suspicious substance or poison (as opposed to the other options: a suspected poisoned badger or a report of general/other info about poisoning) they are asked "is the substance at or very close to a badger sett?" If yes this takes them to
Sett interference > Poisoning or gassing
