### ISSUE TITLE
SC7 and SC10 re poisoning

### ISSUE THREAD

**Issue by DawnBadger** [crsdc/badgerapp#64]
Please add to both poisoning sections 'Any suspected poisoning incidents must be reported to the Health and Safety Executive under their Wildlife Incident Investigation Scheme. You can find full details here [link https://www.hse.gov.uk/pesticides/reducing-environmental-impact/wildlife/wildlife-incident-investigation-scheme.htm] and call 0800 321600 (calls are free).'

**Comment by crsdc** [comment]
Fixed in forthcoming version 1.2.34
