### ISSUE TITLE
Welcome screen text amend

### ISSUE THREAD

**Issue by DawnBadger** [crsdc/badgerapp#68]
1) Can we make the text smaller so it better fits on one page? Really large at mo.

2) In the para re Eng & Wales please add at end 'To report badger crime in Scotland please contact Scottish Badgers [link https://www.scottishbadgers.org.uk/] and use their online form here [link (https://www.scottishbadgers.org.uk/be-involved/report/)] or similar.

**Comment by crsdc** [comment]
Fixed in forthcoming version 1.2.34
