### ISSUE TITLE
Report form missing key persmissions box *URGENT*

### ISSUE THREAD

**Issue by DawnBadger** [crsdc/badgerapp#69]
The reporting form needs to ask for permission to pass the details on to third parties, which is key for sharing info and has to match the online form (https://www.badgertrust.org.uk/report) Please add:

Do you give permission for us to pass on your information to the relevant contacts and authorities for follow-up? Yes/No (however buttons need to work)

**Comment by crsdc** [comment]
Fixed in forthcoming version 1.2.34
