### ISSUE TITLE
Name of the app

### ISSUE THREAD

**Issue by crsdc** [crsdc/badgerapp#7]
I believe we agreed a while ago that the working title should probably not be the public name of the app, and that the name we choose should probably begin with the word "badger".

- Badger Patrol - already in use with a different meaning
- Badger Watch
- Badger Report
- Badger Guardian - suggested by JP or VM?
- Badger Witness - suggested by JP or VM?

Suggest we decide on this before we move to open beta. Not a problem if invited testers (closed beta) see the app with a working title, but once awareness spreads to people we don't know consistency of branding will be needed.

Note that a persistent identifier of the app is (for obscure technical reasons) org.projectbadger.badger, and must always be if we want to maintain continuity of updates once someone has installed the app. This is visible to users in certain circumstances, although not prominently, and not within the app UI itself.

**Comment by DawnBadger** [comment]
Please use Badger Watch

**Comment by crsdc** [comment]
Change was made in v1.2.15. Some caching/sticky behaviour with how the app is listed by phones it's installed on meant the old name was still visible in some circumstances after this, but it seems to be gone now.
