### ISSUE TITLE
Map pin - text re precision? *URGENT*

### ISSUE THREAD

**Issue by DawnBadger** [crsdc/badgerapp#71]
I can see one other comment on this, but the pin drop isn't able to be put or moved to a specific location manually. Do we need to state this explicitly in the text? It will be annoying, and dependant on how far out it is could make the use of it impactical as the tool of choice.

Q - how precise/variable is the pin drop?

**Comment by crsdc** [comment]
This one has been proving tricky to fix. Agree on the importance of getting this right.

**Comment by crsdc** [comment]
Believed fixed after thorough overhaul of the map a few versions ago
