### ISSUE TITLE
App logo

### ISSUE THREAD

**Issue by crsdc** [crsdc/badgerapp#9]
Square crop of BT logo has been used for current alpha releases just so we have something for now.

DV comments:

> Suggest we use a badger paw print instead (fits with patrol name too). I can get this designed if you give me any ratio/format requirements.

Part of my reply from the earlier shared document:

> For any app logo, aspect ratio needs to be **1:1 square**, and we start with a high-res uncompressed **PNG** at **1024x1024** (some sources say 1536x1536 but that may be overkill) which is then transformed in all sorts of ways with rounded corners etc that are applied differently depending on where the logo appears (different phones, different Android/iOS versions, phone itself vs app store etc). Main advice would be to keep it simple and avoid text (icon will be very small in many settings and the launcher will have the name underneath it anyway), avoid white background, and avoid overall shapes that won’t fit well with the rounded corners and other edge cropping that will be applied. I can generate the versions we need from a single 1024x1024 PNG, but if you’re dealing with a graphic designer they’ll know more than me about how to do this well, and main documents to refer to would be [https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/](https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/) and [https://developer.android.com/distribute/google-play/resources/icon-design-specifications](https://developer.android.com/distribute/google-play/resources/icon-design-specifications)

Input encouraged. Suggest we have this fully in place by the time of open beta. If we have a good idea of where we're going we can fairly easily switch to a placeholder that looks more like it before then.

**Comment by DawnBadger** [comment]
I'll ask our designer. I won't be able to pick this up again until back from holiday on 15th Nov, but it's underway.

**Comment by crsdc** [comment]
New logo incorporated in v1.2.15, and bugs that meant the old logo was present in some places were fixed in v1.2.17. The old logo should no longer be visible anywhere now.
